### ISSUE TITLE
Errors since V2.0.0

### ISSUE THREAD

**Issue by Uwe1984** [iobroker-community-adapters/ioBroker.panasonic-viera#138]
Since the update from V1.0.2 to 2.0.0 I get the following errors when I switch off the TV

`<html>
<body>

panasonic-viera.0 | 2021-11-18 20:37:06.269 | error | Exception-Code: ECONNREFUSED: connect ECONNREFUSED 192.168.178.43:55000
-- | -- | -- | --
panasonic-viera.0 | 2021-11-18 20:37:06.269 | error | Error: connect ECONNREFUSED 192.168.178.43:55000 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
panasonic-viera.0 | 2021-11-18 20:37:06.268 | error | unhandled promise rejection: connect ECONNREFUSED 192.168.178.43:55000
panasonic-viera.0 | 2021-11-18 20:37:06.267 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

**Comment by KaosKatte** [comment]
I really like my function to mute the TV and to stop the media player when the phone rings. Unfortunately ioBroker shuts down the Viera instance due to too many failures and boot loops. Is there anything I can do? Is my TV too old (about 11 years)?

panasonic-viera.0 | 2021-12-06 21:13:25.555 | info | terminating -- | -- | -- | --
panasonic-viera.0 | 2021-12-06 21:13:25.023 | error | Exception-Code: ECONNREFUSED: connect ECONNREFUSED 192.168.2.8:55000
panasonic-viera.0 | 2021-12-06 21:13:25.019 | error | Error: connect ECONNREFUSED 192.168.2.8:55000  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
panasonic-viera.0 | 2021-12-06 21:13:25.016 | error | unhandled promise rejection: connect ECONNREFUSED 192.168.2.8:55000
panasonic-viera.0 | 2021-12-06 21:13:25.010 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
panasonic-viera.0 | 2021-12-06 21:13:24.633 | info | starting. Version 2.0.0 in /opt/iobroker/node_modules/iobroker.panasonic-viera, node: v12.22.7, js-controller: 3.3.18

**Comment by Ital-Iener** [comment]
Same here...

2022-03-05 08:36:18.824	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-03-05 08:36:18.821	info	terminating
2022-03-05 08:36:18.308	error	Exception-Code: ECONNREFUSED: connect ECONNREFUSED 192.168.0.66:55000
2022-03-05 08:36:18.308	error	Error: connect ECONNREFUSED 192.168.0.66:55000 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
2022-03-05 08:36:18.307	error	unhandled promise rejection: connect ECONNREFUSED 192.168.0.66:55000
2022-03-05 08:36:18.306	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-03-05 08:36:18.197	info	starting. Version 2.0.0 in /opt/iobroker/node_modules/iobroker.panasonic-viera, node: v14.18.2, js-controller: 3.3.22
